name: Release & Publish Artifacts

on:
  release:
    types: [published]
  workflow_dispatch: # 👈 Manual trigger support

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v4

      - name: ☕ Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: ⚙️ Make Gradle executable
        run: chmod +x ./gradlew

      - name: 🏗️ Build with Gradle
        run: ./gradlew clean build

      - name: 📤 Upload all files in target/ to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/**

      - name: 🚀 Upload all target/ files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          files: target/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
